### ISSUE TITLE
Game Crashes every 25-40 minutes

### ISSUE THREAD

**Issue by PizzaTowerGuy** [GithubSPerez/pt-new-level-editor#10]
Whenever I start the game, it starts out well, but it gradually worsens. The first issue that appears after approximately 10 minutes of gameplay on Level editor is, Ladders and other items begin to get very jammed. Second, after roughly 25 minutes, tiles begin to lag, making it tough to position them, and third, after about 40 minutes of time spent playing, My entire computer crashes, and I can't even turn it off; I have to walk all over my house simply to disconnect the computer plug and switch it back on.

**Comment by GithubSPerez** [comment]
Could you share how much memory the game is using when hitting those time marks? I'm referring to the memory value that shows up on the task manager

**Comment by hedgeys** [comment]
having the same issue, after some time, memory reachs 100% and (atleast) my pc and game crashes
![image](https://github.com/GithubSPerez/pt-new-level-editor/assets/133594590/6e7dfe98-c35f-4d29-881f-a0c8a86c5a79)

**Comment by GithubSPerez** [comment]
Alright that's what I wanted to confirm. The update I'm working on will fix this issue, the game will from now on never use more than 2.6 gb of memory. The current public version had memory leak issues where surfaces would remain on memory even after the game stopped using them, it's all fixed for the release of beta 2

**Comment by GithubSPerez** [comment]
fixed on beta 2
