### ISSUE TITLE
Mouse misalignment

### ISSUE THREAD

**Issue by rrhusdgbtbu** [GithubSPerez/pt-new-level-editor#11]
the mouse is moving to halfway of where it's supposed to go, shoved into the top-left corner.

pic below is my real mouse (not visible, but it's all the way on the right border of the window) and the in-game mouse clipping out of some weird frame???
![Pizza Tower 5_17_2023 9_58_44 PM](https://github.com/GithubSPerez/pt-new-level-editor/assets/80306366/d75e9b1c-d85a-4600-981e-1c7f211a9edb)
i don't know if it's a bug with the editor, or the way i patched it, what's going on?

EDIT: 2 things,
1: the entire rest of the menu is cut off from like halfway for whatever reason
2: when i alt-tab to something else, it fixes, but when i focus back, it breaks

**Comment by 06NinjaKid06** [comment]
its because your in windowed mode change to fullscreen

**Comment by rrhusdgbtbu** [comment]
shit thanks
