### ISSUE TITLE
obj_secretmetalblock isn't in the editor

### ISSUE THREAD

**Issue by Idunno1** [GithubSPerez/pt-new-level-editor#12]
Self-explanatory. There are also two obj_onewaybigblocks in the blocks tab, was one supposed to be the secret metal block?

![image](https://github.com/GithubSPerez/pt-new-level-editor/assets/8219159/ea81988e-6dd0-4b3d-8e1a-000586ed90b6)

**Comment by GithubSPerez** [comment]
it's present on beta 2
