### ISSUE TITLE
Flipped obj_solids don't render properly in the editor

### ISSUE THREAD

**Issue by Idunno1** [GithubSPerez/pt-new-level-editor#13]
If you flip obj_solid, the flip happens, but it's not shown in the editor. Maybe just disable flipping it entirely?

![image](https://github.com/GithubSPerez/pt-new-level-editor/assets/8219159/8e93ecf0-20f7-4c18-a30e-357db0dfb8b8)
![image](https://github.com/GithubSPerez/pt-new-level-editor/assets/8219159/59fb240b-dd4d-4dcb-bbbd-b792657a1b8d)

**Comment by GithubSPerez** [comment]
fixed on beta 2
