### ISSUE TITLE
Mod won't work in Pizza Tower or xdeltapatcher

### ISSUE THREAD

**Issue by FaintlyFeminine** [GithubSPerez/pt-new-level-editor#14]
Whenever I launch the mod through Pizza Oven 
it says this:
ERROR in
action number 1
of Create Event
for object <undefined>:

Error attempting to load wad file with unexpected size 58720256 szFORM 94920009

And when I xdelta patched the mod it showed up the same thing through steam.
Anybody Have solutions?

**Comment by 06NinjaKid06** [comment]
this happens for every mod, wait a few days, and it should be fixed
