### ISSUE TITLE
cursor is inaccurate in editor

### ISSUE THREAD

**Issue by justinsly** [GithubSPerez/pt-new-level-editor#15]
you can see what i mean in this screenshot 
![image](https://github.com/GithubSPerez/pt-new-level-editor/assets/134002548/219fe76e-694d-48f7-8cd3-ade7d2957505)
as you can see, the higher i put the cursor, the more inaccurate it becomes, it gets annoying after a while, would like seeing it get fixed in beta 2 

(would also like it if you made the editor usable in windowed mode)

**Comment by Plackys** [comment]
go to fullscreen not windowed

**Comment by justinsly** [comment]
> go to fullscreen not windowed

ik about the mod being broken in windowed, but the main issue still happens in fullscreen

**Comment by GithubSPerez** [comment]
fixed on beta 2
