### ISSUE TITLE
the theme for the save select screen doesnt play after coming back from the tower editor

### ISSUE THREAD

**Issue by justinsly** [GithubSPerez/pt-new-level-editor#16]
title speaks for itself

**Comment by meforas** [comment]
same man

**Comment by 06NinjaKid06** [comment]
same

**Comment by ThePlanZ** [comment]
Yeah this happens SOMETIMES, but not all the time.

**Comment by JDHjinxlovr** [comment]
just happened to me

**Comment by 06NinjaKid06** [comment]
> Yeah this happens SOMETIMES, but not all the time.

for me it happens all the time

**Comment by justinsly** [comment]
please keep issues clear of replies that are just "same bro"👍
