### ISSUE TITLE
WHAT DID I DO HELP

### ISSUE THREAD

**Issue by 06NinjaKid06** [GithubSPerez/pt-new-level-editor#18]
I AM SO CONFUSED
WHAT

https://github.com/GithubSPerez/pt-new-level-editor/assets/104595016/0e2ac63a-f134-450a-a9e1-d46530789490

**Comment by 06NinjaKid06** [comment]
if i go in it it takes me to room number -4 and crashes the game

**Comment by Plackys** [comment]
maybe you have the noise satelite (which crash the game if you load it into the game)

**Comment by GithubSPerez** [comment]
the issue section on this page is for bug reports, it's not a help forum
