### ISSUE TITLE
Tiles removed from secret blocks come back after room switches

### ISSUE THREAD

**Issue by Idunno1** [GithubSPerez/pt-new-level-editor#21]
See video:

https://github.com/GithubSPerez/pt-new-level-editor/assets/8219159/f4f3cc6e-c592-4f0b-bd16-8664b3d30dea

The weird palette tiles on the right appeared after I right clicked to tab back into the window, btw

**Comment by 06NinjaKid06** [comment]
what are those tiles above secret tiles

**Comment by Idunno1** [comment]
> what are those tiles above secret tiles

wdym

**Comment by 06NinjaKid06** [comment]
> > what are those tiles above secret tiles
> 
> wdym

the ones with the f-word I didn't know you could make your own

**Comment by Idunno1** [comment]
> > > what are those tiles above secret tiles
> > 
> > 
> > wdym
> 
> the ones with the f-word I didn't know you could make your own

oh yeah, that's actually the second frame of the medieval tileset that you can't normally access in the editor, so i exported it with undertalemodtool and added it as a custom tileset
