### ISSUE TITLE
(ignore i just fixed my wifi) level editor not extracting editor_assets at all when first install

### ISSUE THREAD

**Issue by mariogithubing** [GithubSPerez/pt-new-level-editor#23]
https://github.com/GithubSPerez/pt-new-level-editor/assets/108615329/eef04bcb-7282-48f0-a867-fddaaa882307

**Comment by mariogithubing** [comment]
fixed my internet pls remove this

**Comment by 06NinjaKid06** [comment]
you know YOU can close this issue right?
