### ISSUE TITLE
Flipped one way destroyables don't work correctly

### ISSUE THREAD

**Issue by lerp32** [GithubSPerez/pt-new-level-editor#26]
When flipping one way destroyables, their solid side doesn't flip with them, resulting in not only being able to partially walk through them, but also being able destroy them from what should be their solid side

https://github.com/GithubSPerez/pt-new-level-editor/assets/80685036/4422eb37-182b-4a86-ad49-6d817a5d152e

**Comment by 06NinjaKid06** [comment]
i have this bug to its annoying
