### ISSUE TITLE
Weird bug where Peppino isn't there and camera is following invisible player falling down the level

### ISSUE THREAD

**Issue by JDHjinxlovr** [GithubSPerez/pt-new-level-editor#27]
Basically, theres a bug where when I enter this room Peppino isn't there and the player is an invisible object thats falling down and going through all collisions. I can only make the invisible object ground pound while falling. The bug only happens if I enter the room. 

Live footage on yt cause github sucks i think: https://youtu.be/QQJ0CH4Pwrk

**Comment by 06NinjaKid06** [comment]
did you set a target door?

**Comment by GithubSPerez** [comment]
this happens when you don't set up warps correctly.
