### ISSUE TITLE
OBJ_LADDER Missing Texture

### ISSUE THREAD

**Issue by CoboltTec** [GithubSPerez/pt-new-level-editor#28]
OBJ_LADDER is invisable

**Comment by CoboltTec** [comment]
also can you make OBJ_SOLID and OBJ_SLOPE visible like in the original pizza tower editor so i dont have to put tiles over them to see the blocks

**Comment by AbsurdCoolMan** [comment]
OBJ_LADDER is supposed to be invisible, that's why it's in the collisions category.
