### ISSUE TITLE
wrong rat collision

### ISSUE THREAD

**Issue by NeoCat3** [GithubSPerez/pt-new-level-editor#30]
the stupid rat's collision IS in the right place, but it's sprite is moved to a different spot
didn't really know how to put all that into the title LOL

https://github.com/GithubSPerez/pt-new-level-editor/assets/134071088/85134aba-9a6c-43cc-a6e2-e2c816be5ecb

**Comment by 06NinjaKid06** [comment]
someone else had this issue as well and he said just make sure you didn't have the rat flipped

**Comment by NeoCat3** [comment]
> someone else had this issue as well and he said just make sure you didn't have the rat flipped

oh alright then thanks
