### ISSUE TITLE
Collisions, Rats, and an Issue

### ISSUE THREAD

**Issue by Itsyaboi1** [GithubSPerez/pt-new-level-editor#4]
The video explains it. (had to compress it to fit the 10 MB file limit)

https://github.com/GithubSPerez/pt-new-level-editor/assets/133723391/96efc254-4aac-4753-a0e2-7dc5840afcbf

**Comment by 06NinjaKid06** [comment]
the tiles thing always happens to me but I have never seen the collision change?

**Comment by GithubSPerez** [comment]
ok the collision bug with obj_solid is fixed on beta-2 but idk about the rat one, you'll just have to edit the rat to not be horizontally flipped.
