### ISSUE TITLE
Unable to pass arrays into variables

### ISSUE THREAD

**Issue by lerp32** [GithubSPerez/pt-new-level-editor#41]
Certain objects like obj_arenadoor and obj_tvtrigger, heavily utilize arrays, so being unable to set them is detrimental to their functionality.
While its not required that the ability to pass arrays into variables is added, it'd be a rather nice addition for anyone that wants to use objects like the ones I listed above.

**Comment by GithubSPerez** [comment]
neither of those 2 objects are included in the default objects.json, whichever objects I can't implement at the moment will not get included. eventually there will be a way to pass more complex values to objects but this page is for bug reports, not feature requests
