### ISSUE TITLE
game doesnt wanna launch after i patched the update

### ISSUE THREAD

**Issue by justinsly** [GithubSPerez/pt-new-level-editor#43]
title

**Comment by justinsly** [comment]
noticed that 2.1 is out lemme try to patch that and see if it makes it any better

**Comment by GithubSPerez** [comment]
The issues section of this page is not for troubleshooting. But what's probably happening is that you need to uninstall the mod and then install one single version.

**Comment by justinsly** [comment]
will try that, also one more thing, do you know what causes deltapatcher to not be able to patch the mod unless i disable checksum validation?

**Comment by GithubSPerez** [comment]
lol that's exactly it, there's no mod that will work if the checksum validation fails. You're probably trying yo patch the update over the .win file that's already patched with the previous version, which is not the way to do it (and that's why the validation is failing)
