### ISSUE TITLE
Ladder Teleports Player To The Bottom

### ISSUE THREAD

**Issue by CoboltTec** [GithubSPerez/pt-new-level-editor#44]
https://github.com/GithubSPerez/pt-new-level-editor/assets/134158316/7fc2a720-f932-4f48-9870-2b2ab508216e

**Comment by LoldReal** [comment]
Just jump off the ladder.

**Comment by Gostar64** [comment]
I think you have to put a platform on the top ladder

**Comment by Busybody64** [comment]
try putting 1 separate ladder object for each tile instead of one giga stretched one

**Comment by GithubSPerez** [comment]
fixed on beta 3
