### ISSUE TITLE
mistake to want to enter a room

### ISSUE THREAD

**Issue by Alejo5205** [GithubSPerez/pt-new-level-editor#51]
I have spasified it and everything, and even so, this happens to me, what do I do?

https://github.com/GithubSPerez/pt-new-level-editor/assets/92231866/7c74ba12-1fe2-4031-9851-ba02786fafce

https://github.com/GithubSPerez/pt-new-level-editor/assets/92231866/041dfbb0-a6cf-41bd-b833-632a28610709

**Comment by GithubSPerez** [comment]
read the wiki on warps https://github.com/GithubSPerez/pt-new-level-editor/wiki/Warps
the only warp that needs the targetDoor variable is hallway, none of the others work with it.
