### ISSUE TITLE
Going inside a secret while the escape continues playing the escape theme

### ISSUE THREAD

**Issue by EntityPlantt** [GithubSPerez/pt-new-level-editor#52]
I have a level that doesn't have a song in the rooms, but it has a song in the secrets. When I get into a secret from a room in the escape sequence the escape theme continues playing. Maybe it's because of the lack of song in the main rooms, that's why I pointed it out.

**Comment by GithubSPerez** [comment]
I purposely made it so the escape theme continues to play on secrets, both because it was easier to code and because I always thought it would be better to not disrupt the escape music

**Comment by EntityPlantt** [comment]
Nice, okay, but I thought for convenience if we wanted to play the escape theme in the secrets we would just set it to that song, or maybe if in the future we want to add a special escape secret music to that place. Guess there's always the war timer 😂

A question about the coding: why not with the play button replace the John Gutter level with the custom one and then, when pressed <kbd>Esc</kbd>, return back the original John Gutter in the files. That way the game itself will care about handling events, eg. music in secrets during escape.
