### ISSUE TITLE
How do I make it so tiles aren't on top of things like level gates?

### ISSUE THREAD

**Issue by gmoduser38** [GithubSPerez/pt-new-level-editor#63]
So what happens is I'm trying to make a level, and I want to decorate the background with the decoration tiles, but when I try putting the level gate in any layer or the tile on any other layer, the tile always is on top of the level gate. Is this intended? Because I don't think it should be like that...
![Screenshot 2023-06-02 165958](https://github.com/GithubSPerez/pt-new-level-editor/assets/134816662/bc81f54a-c819-4ef1-92ef-3f5cfd607ddb)
![Screenshot 2023-06-02 170039](https://github.com/GithubSPerez/pt-new-level-editor/assets/134816662/61176f46-62dc-4547-9cf3-41a3a1743f83)

**Comment by hedgeys** [comment]
set layer depth to false

**Comment by GithubSPerez** [comment]
Set the "use layer depth" variable to true
