### ISSUE TITLE
Warps that aren't hallways teleport Peppino to a random position

### ISSUE THREAD

**Issue by gmoduser38** [GithubSPerez/pt-new-level-editor#65]
For some reason, whenever I try using the Pizza Box warp, with the letter object or not, with the variable set or not, it still teleports me to this random position in the room.
This wasn't happening in the older version if I remember correctly. Am I doing something wrong?

https://github.com/GithubSPerez/pt-new-level-editor/assets/134816662/e3a75505-958f-4584-9e88-ad79ed564cf6

**Comment by GithubSPerez** [comment]
That's because your putting different letters on the pizza boxes, both of them should be D (or both should be E)
The targetdoor variable only has an effect on hallways.
