### ISSUE TITLE
Level is un P-Rank-able

### ISSUE THREAD

**Issue by CrabulousGithub** [GithubSPerez/pt-new-level-editor#71]
My level for some reason will not P-Rank, the level is so close to done but this issue is really bugging me. I don't know if has something to do with the s-rank score, the secret rooms, treasure, or what.

**Comment by CrabulousGithub** [comment]
Sorry, forgot the level. https://drive.google.com/file/d/1rMvO0oDyKnxQNNqTnjfacbQv7yZK8V9q/view?usp=sharing

**Comment by bubbyboytoo** [comment]
You need an enemy in the first room to start the combo with.

**Comment by CrabulousGithub** [comment]
> You need an enemy in the first room to start the combo with.

Thank you, this has been bugging me for a while.
