### ISSUE TITLE
Crashes when starting the game

### ISSUE THREAD

**Issue by Coderexehasstopped** [GithubSPerez/pt-new-level-editor#74]
ERROR in
action number 1
of Async Event: HTTP
for object obj_modAssets:

Push :: Execution Error - Variable Index [0] out of range [0] - -7.result(101177,0)
at gml_Object_obj_modAssets_Other_62
############################################################################################
gml_Object_obj_modAssets_Other_62 (line -1)

**Comment by hedgeys** [comment]
same here

**Comment by MilkWithCereal** [comment]
is this a global issue?

**Comment by hedgeys** [comment]
it is

**Comment by hashoom15** [comment]
i have this exact same problem

**Comment by Ivan951236** [comment]
i guess everyone at this point is getting this exact error

**Comment by bubbyboytoo** [comment]
I wonder what caused it all of a sudden. Did PT get a stealth update or something?

**Comment by hedgeys** [comment]
well, you can fix the error by turning off your internet, entering CYOP and then turning it on again, the tower browser doesn't work, but cyop does

**Comment by Coderexehasstopped** [comment]
I think it's caused by the tower browser

**Comment by GithubSPerez** [comment]
just realeased a hotfix for this, beta 3.5
