### ISSUE TITLE
[URGENT] Mod breaks Steam Cloud

### ISSUE THREAD

**Issue by freakalope** [GithubSPerez/pt-new-level-editor#80]
This appears to cause different files to be registered to the remotecache.vdf file within C:\Program Files (x86)\Steam\userdata\(user)\2231450 . From what I can gather, the problem seems to stem from the .ini files this mod stores in the same master PizzaTower_GM2 directory.

I was able to correct this by forcibly cleaning out my steam cloud and resetting the contents of remotecache.vdf,, and deleting the contents of my AppData PizzaTower_GM2, then restoring them from a backup.

This seems like a pretty serious problem, as any future changes to saves do not get backed up properly. In addition, users who use multiple devices such as Steam Deck cannot access their data cross platform anymore. I don't know if it would be possible to store this mod's data in a different location, but it may be a good idea to avoid future conflicts.

One option potentially worth looking into is I saw that the [ASLM mod on Game Banana](https://gamebanana.com/mods/430774) stores its data in a completely separate AppData folder. Maybe something similar could be achieved?

**Comment by freakalope** [comment]
Mod no longer updated

**Comment by RotKingJoey** [comment]
Mod no longer updated
