### ISSUE TITLE
Secret destroyables sometimes don't delete tiles

### ISSUE THREAD

**Issue by lerp32** [GithubSPerez/pt-new-level-editor#9]
For some reason, secret destroyables just don't delete tiles sometimes

https://github.com/GithubSPerez/pt-new-level-editor/assets/80685036/11c04e8e-ab0c-4d73-a4f7-0164de1001fd

**Comment by rrhusdgbtbu** [comment]
quite annoying, yes. but, personally, i came up with my own solution:

1: replace secret bricks with regular bricks
2: select tiles mode and press right until the layer says (secret)
3: cover up the destroyable bricks

presto, now they'll only be revealed when peppino steps into them.

**Comment by GithubSPerez** [comment]
fixed on beta 2
